create table if not exists conta (
        id bigint generated by default as identity,
        nome varchar(255),
        valororiginal DECIMAL,
        datavencimento DATE,
        datapagamento DATE,
        valorcorrigido DECIMAL,
        quantdddiasatraso DATE,
        primary key (id)
    );

